### ISSUE TITLE
Fix freq sleeping to subtract time spent for computations

### ISSUE THREAD

**Issue by chrberger** [chalmers-revere/opendlv-device-ultrasonic-srf08#1]
https://github.com/chalmers-revere/opendlv-device-ultrasonic-srf08/blob/master/src/opendlv-device-ultrasonic-srf08.cpp#L81

**Comment by bjornborg** [comment]
This is now fixed by using the built-in function in libcluon
https://github.com/chalmers-revere/opendlv-device-ultrasonic-srf08/blob/master/src/opendlv-device-ultrasonic-srf08.cpp#L199
